"""add stats eligibility to game sessions

Revision ID: 76073af34e12
Revises: b0e8e797a9d3
Create Date: 2026-09-10 13:44:40.411486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76073af34e12'
down_revision: Union[str, Sequence[str], None] = 'b0e8e797a9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "game_sessions",
        sa.Column(
            "stats_eligible",
            sa.Boolean(),
            nullable=True,
        ),
    )

    # Existing game sessions were normal daily games,
    # so they should remain eligible for statistics.
    op.execute(
        """
        UPDATE game_sessions
        SET stats_eligible = TRUE
        WHERE stats_eligible IS NULL
        """
    )

    op.alter_column(
        "game_sessions",
        "stats_eligible",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'stats_eligible')
    # ### end Alembic commands ###
